### ISSUE TITLE
Emphasize hash selection dropdown as an interactive control (styling)

### ISSUE THREAD

**Issue by crashdemons** [tweqx/3301-hash-alarm#16]
![image](https://user-images.githubusercontent.com/3233238/114088034-335b8500-987a-11eb-9e4b-a49d5eac071c.png)
This may be system-dependent but from this image of the popup menu, it is not obvious at a glance that the "Most Hashes" is a dropdown or even clickable.   A thin light border, or even a background would better emphasize this.

Personally I can tell what you meant, but others might not be able to.

**Comment by tweqx** [comment]
That's indeed not expected, and system dependent (?)

Here is how it looks on my browser : 
![Expected look](https://user-images.githubusercontent.com/29614762/114091936-97516e00-98b9-11eb-9e5f-e228d791b102.png)
The font doesn't seem correct either...

I'll correct the CSS code to copy the current default style on my browser.

**Comment by tweqx** [comment]
Fixed with c568ad3b431b5d59a749f79b7b9e2fa0da6195eb, can you confirm it's working now ?
There is now a 'background-color', 'DejaVu-Sans' is loaded and used as the font.

**Comment by crashdemons** [comment]
I can only barely make out the background around the selection box personally.  Would `#e6e5e4` work? for me that is a lot more visible.

maybe my display just sucks.

**Comment by tweqx** [comment]
`#e6e5e4` looks great.
Pushed d925fb4a64c788f0c412e302a13749d9e83fd439, feel free to close this issue if it looks better on your display.

**Comment by crashdemons** [comment]
looks good 👍
